### ISSUE TITLE
Installation instructions missing

### ISSUE THREAD

**Issue by janikarh** [plumdog/flask_table#106]
The documentation should have installation instructions. It might not be obvious to new users, especially if one is new to Python ecosystem altogether.

**Comment by plumdog** [comment]
Hi @janikarh,

Yeah, I agree. #107 just adds the `pip install` to the README. Can you think of anything else that it might be useful to include?

**Comment by plumdog** [comment]
There's already a reasonably fulsome [directory of examples](https://github.com/plumdog/flask_table/tree/master/examples) a few of which do use a Flask app, and a bit in the README about them. I've added a note about them in the Quickstart bit because they were only in at the very end of the README.

**Comment by janikarh** [comment]
Can't quite believe, how I missed that :)

Good addition nonetheless.
