### ISSUE TITLE
LinkCol contents becomes 'Name'

### ISSUE THREAD

**Issue by rfkortekaas** [plumdog/flask_table#19]
When using the LinkCol type the link gets the name of the LinkCol instead of the contents from the item.

**Comment by plumdog** [comment]
If you set `attr='my_attribute_name'` on your `LinkCol`, it should use the value from that attribute as the text for the link. It uses the name of the column as a fallback. Unlike with other columns, it does not borrow the attribute that you give the column in the table class to get the attribute from the item for the td.

[This example](https://github.com/plumdog/flask_table/blob/master/examples/simple_app.py) might be useful. In particular, if we removed `attr='name'` from the `LinkCol` in that example, we would just get name of the column, not the name attribute from the item. But we don't need to do this for the description field.

I've been meaning to write some more docs for the different Col-types because of edge-cases like this.

**Comment by plumdog** [comment]
I've added some [better docs](https://github.com/plumdog/flask_table#more-about-linkcol) on this, because I had to stare at the code a bit to work out what was going on. Hopefully this is helpful!

**Comment by plumdog** [comment]
Closing - let me know if there's anything else you want to know.
