### ISSUE TITLE
Create empty table

### ISSUE THREAD

**Issue by sergani** [plumdog/flask_table#32]
Hi there,
For some "odd?" reason I need to create an empty table, by that I mean no <td> and <tr>. Just <table> and the header is required.
Is that possible?

Thanks
//M

**Comment by plumdog** [comment]
There's not a lovely way to do it, but you could create a subclass of `Table` that overrides [the `__html__` method](https://github.com/plumdog/flask_table/blob/master/flask_table/table.py#L85) to remove the `if tbody` bit, so that it always ignores the `self.no_items` stuff.

I could be easily persuaded to add an `allow_empty` option to `Table`, which would default to `False`, but if it were true would give an empty table, rather than the "No Items" `<p>` which might be nicest.

**Comment by sergani** [comment]
You should be persuaded then haha
