### ISSUE TITLE
jinja not rendering table?

### ISSUE THREAD

**Issue by 0x8** [plumdog/flask_table#76]
I am writing something up based on the docs but I have an issue I can't figure out.

Basically the table is created fine, and when explicitly printing the `<table>.__html__()` I can see it is generating the html but Jinja is not replacing the tag with the html. For simplicity sake I have:

```
class myTable():
    <stuff>

hTable = myTable(myTable.getItems()) # the getItems method just runs a static query and fills the results
```

Then in the html file, lets call it myHtml.html:
```
<stuff>

{{ hTable }}

<other stuff>
```

Is this not correct? I'm not terribly sure.

As I said, when I do
```
print(hTable.__html__())
```

it is definitely producing the correct html but maybe I am missing how to pass it to jinja?

**Comment by plumdog** [comment]
I suspect you're right and the problem is in passing the variables to the Jinja template and it is defaulting to nothingness. You could test this by changing `hTable = <actual code...>` into `hTable = 'my hTable here'`. Then if this debug string doesn't appear then it's not a table problem, it's a variables-to-template problem.

If it is a variables-to-template problem then feel free to post a code snippet from your view and I'll take a look.

**Comment by 0x8** [comment]
No, I'm terribly sorry it was my mistake, I actually wasn't passing the var correctly in flask. I'm sorry.

Essentially the calling code in flask does something like (using the example above):

```
<myTableClass>

@app.route('/myPage'):
     hTable = myTable(myTable.getItems())
     return render_template('myPage.html', hTable = hTable)
```

The problem I had was I was omitting the `hTable=hTable` portion from the route function in flask. This solved my problem. Thanks mate!

**Comment by plumdog** [comment]
:smile: No worries! Glad you got it sorted.
