### ISSUE TITLE
def "sort_url" for dynamic tables

### ISSUE THREAD

**Issue by elgaucho79** [plumdog/flask_table#85]
Hi,
-- Warning, May be a greenhorn qustion -- :-)
I have designed a dynamic table based on create_table function and try to use the sort functionality as well. As per documentation the sort_url function is specified to the class Table itself. But with dynamic tables I do not a class like class TableCls(Table): 
Where do I define the "def sort_url" function when using dynamic tables created with: 
    TableCls = create_table('TableCls') ?

regards#
Michael

**Comment by plumdog** [comment]
Hi!

It turns out that the answer is: yes, you can do this, but it's a bit sneaky.

The `options` argument that can be passed into `create_table` is a dictionary, and those key-values are set as attributes on the class it creates. This works for things like `allow_sort` and `allow_empty` etc, but also works for defining methods, because as far as Python is concerned, they are basically the same.

For example, the table in [the `sortable.py` example](https://github.com/plumdog/flask_table/blob/master/examples/sortable.py) is the same as:
```python
def dynamic_sort_url(self, col_key, reverse=False):
    if reverse:
        direction = 'desc'
    else:
        direction = 'asc'
    return url_for('index', sort=col_key, direction=direction)

# alternatively, if you like using lambda
dynamic_sort_url = lambda self, col_key, reverse=False: url_for('index', sort=col_key, direction='desc' if reverse else 'asc')

SortableTable = (
    create_table(
        'SortableTable',
        options=dict(
            allow_sort=True,
            sort_url=dynamic_sort_url))
    .add_column('id', Col('ID'))
    .add_column('name', Col('Description'))
    .add_column('link', LinkCol('Link', 'flask_link', url_kwargs=dict(id='id'), allow_sort=False))
)
```

Which works, but is maybe a bit on the ugly side.

Perhaps a neater way would be:

```python
class SortableTableBase(Table):
    def sort_url(self, col_key, reverse=False):
        if reverse:
            direction = 'desc'
        else:
            direction = 'asc'
        return url_for('index', sort=col_key, direction=direction)

SortableTable = (
    create_table(
        'SortableTable',
        base=SortableTableBase,  # A custom base class for the dynamic table
        options=dict(
            allow_sort=True))
    .add_column('id', Col('ID'))
    .add_column('name', Col('Description'))
    .add_column('link', LinkCol('Link', 'flask_link', url_kwargs=dict(id='id'), allow_sort=False))
)
```

Hopefully one of those will work for you, and maybe you can see from the examples above why each one works (if you copy the contents of the `sortable.py` example and copy in my code snippets from above to replace the table, hopefully they'll work).

And so it turns out that this is absolutely *not* a greenhorn question - we're in Metaclass-land here. And this could really do with being made clearer in the docs, so I'll add that.

Thanks for your question! I hope my answer helps.

**Comment by elgaucho79** [comment]
Thank you very much. Works so far. 
Using the second approach based on "class SortableTableBase(Table)" I wonder if the 'index' in return url_for statement can be defined dynamic as well? Otherwise I would have to declare this class each time for different dynamic table used on different url-pages.

`return` url_for('dynamic', sort=col_key, direction=direction)`

regards
Michael

**Comment by plumdog** [comment]
You can, because Python lets you declare classes dynamically. If instead of just declaring the base class, you put it in a function, you have what I might call a class factory.

For eg
```python
def get_table_base_class(sort_url_name)
    class SortableTableBase(Table):
        def sort_url(self, col_key, reverse=False):
            if reverse:
                direction = 'desc'
            else:
                direction = 'asc'
            return url_for(sort_url_name, sort=col_key, direction=direction)
    return SortableTableBase

# then

SortableTable = (
    create_table(
        'SortableTable',  # you might want to make this value be different for different pages - might make debugging nicer
        base=get_table_base_class(sort_url_name='index'),  # or pass in some other url name here
        options=dict(
            allow_sort=True))
    .add_column('id', Col('ID'))
    .add_column('name', Col('Description'))
    .add_column('link', LinkCol('Link', 'flask_link', url_kwargs=dict(id='id'), allow_sort=False))
)
```

Hope that's helpful.

**Comment by austinhoag** [comment]
This is still not in the docs.
