### ISSUE TITLE
aligning cell contents (left, right, center, top, botton...)

### ISSUE THREAD

**Issue by elgaucho79** [plumdog/flask_table#86]
Hi, 

I created a dynamic table and the header-labels are wider than the individual contents of the rows. (see attachment)
![padding](https://user-images.githubusercontent.com/32534197/34197108-46c1703a-e565-11e7-9007-24feb7c95fb5.png)
I am able to format the values based on python 'format coding' but I seem not to be able to 'right-align' the values with this coding. He seems to ignore '>' or not supported with flask_table at all?

value assignment to flask_table variable: 
`list[entry.name] = '{:>,.2f}'.format(value).replace(",", "X").replace(".", ",").replace("X", ".")` 

Is there a way to specify the position (left, right, center, top, bottom) of the values in the cells?

regards
Michael

**Comment by plumdog** [comment]
Hi Michael! Really glad you're using flask-table, hope I can help you.

Using Python's formatting and the `>` and `<` operators adds whitespace to a string, which will the be ignored when the browser renders the HTML which is why that isn't working. To tackle the alignment you would need to turn to CSS instead, and you can add classes to the columns in your table using the `column_html_attrs` keyword (and `th_html_attrs` and `td_html_attrs`).

For example (you should be able to run this file and experiment):
```python
from flask_table import Table, Col
from flask import Flask, render_template_string

app = Flask(__name__)

class ItemTable(Table):
    colA = Col('ColA', column_html_attrs={'class': 'colA'})  # apply to both <th> and <td>s
    colB = Col('ColB', th_html_attrs={'class': 'colB'})  # apply just to the <th>
    colC = Col('ColC', td_html_attrs={'class': 'colC'})  # apply just to the <td>s

DEMO_TEMPLATE_STRING = '''
<html>
  <head>
    <style>
      .colA, .colB { text-align: right; }
      .colC { text-align: center; }
    </style>
  </head>
  <body>{{ table }}</body>
</html>
'''

@app.route('/')
def index():
    items = [
        dict(colA='1', colB='long-thing-here1', colC='1'),
        dict(colA='2', colB='long-thing-here2', colC='2'),
    ]
    table = ItemTable(items)

    return render_template_string(DEMO_TEMPLATE_STRING, table=table)

if __name__ == '__main__':
    app.run(debug=True)
```

Would generate HTML (for the table) like:
```html
<table>
    <thead>
        <tr>
            <th class="colA">ColA</th>
            <th class="colB">ColB</th>
            <th>ColC</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="colA">1</td>
            <td>long-thing-here1</td>
            <td class="colC">1</td>
        </tr>
        <tr>
            <td class="colA">2</td>
            <td>long-thing-here2</td>
            <td class="colC">2</td>
        </tr>
    </tbody>
</table>
```
with the CSS adjusting the alignment for the elements with the classes.

There's another example about using these keyword arguments to put attributes on the `<th>`s and the `<td>`s here: https://github.com/plumdog/flask_table/blob/master/examples/column_html_attrs.py

Hope some of that is helpful, let me know if you have any other questions.

**Comment by elgaucho79** [comment]
Thanks Plumdog,

works in a way and I played around with it and discovered that `td_html_attrs=..` works brilliant and he is aligning and coloring the values in the right way.
But trying to use `th_html_attrs=...` he is only aligning the header according to style but he ignores color. Header remains dark blue.
I tried also using `column_html_attrs=` to force header and items on the same style. Result is the same. Items are aligned and colored correct and header is aligned correct but having wrong color.

my code:
![image](https://user-images.githubusercontent.com/32534197/34298863-1dbeebc4-e720-11e7-8d32-047d79f3d82e.png)

Result:
![image](https://user-images.githubusercontent.com/32534197/34298894-3f81cde4-e720-11e7-8682-e36212c89a56.png)

Any idea?

**Comment by plumdog** [comment]
The reason the headers are staying blue is because they are `<a>`s, and so the browser is treating them a bit differently - by default they don't inherit their colour from their parent.

See https://stackoverflow.com/questions/1144931/when-will-a-tag-not-inherit-color-attribute-of-parent-tag for more. I think you might find that adding `th a { color: inherit; }` to your CSS will fix this.

----------------

But `vertical-align: top` should work just fine. I can't see it in the CSS in your example above, but make sure that the HTML you're generating is what you expect it to be, and that you can see the CSS being applied to the right elements when you inspect the table in your browser.

**Comment by elgaucho79** [comment]
Thanks. That was helping. Colors are now getting right with your support but I still struggle with vertical alignment.
He doesn't like it even I put this into the `th a { color: inherit; vertical-align: inherit}`
Was hoping to force the vertical-align as well.

I inspected the table in HTML and to me it looks OK and the class is listed. He ignores the vertical alignment for both, header and items. It seems he puts header on vertical-align: bottom and items 'top'. e.g. column 'fm_id'.
 Please find the HTML bit below:

code:
![image](https://user-images.githubusercontent.com/32534197/34321534-840c24fe-e811-11e7-9ef8-89dc00a341d1.png)

HTML part for header:
![image](https://user-images.githubusercontent.com/32534197/34321556-1c7e9dde-e812-11e7-8945-d987a56525d3.png)

result (not vertical-aligned):
![image](https://user-images.githubusercontent.com/32534197/34321560-396c68e0-e812-11e7-86b4-94aa6ef85763.png)

Hope to get a last support if you may see something that I still make wrong.
Thank you so much.
Michael

**Comment by plumdog** [comment]
I (approximately) copied your HTML and CSS and the alignment worked as I'd expect. See here: https://jsfiddle.net/0xz68594

So I think that you've got some other CSS happening. Based on the `<table class="table table-striped ...">` I think you're using Bootstrap.

Bootstrap does some funny things with vertical alignment (TIL!) see here: https://getbootstrap.com/docs/4.0/utilities/vertical-align/ (make sure you look at the docs for the right version, btw).

So I added this to my bit of testing code, and vertical align stopped working. When I added the special bootstrap `align-top` class, vertical alignment worked again - see https://jsfiddle.net/3y7ceh4j/1/

Hope that's helpful!

**Comment by elgaucho79** [comment]
Hi Andrew,
thanks for the hint. I should have notice that I use Bootstrap and was hoping not to have any conflicts with it. However, if vertical alignment is defined in bootstrap already, I am gonna use this from there. And it's working fine now. :-)
Thank you so much,

regards
Michael
